# GENERATED from the 0.10 test suite (legacy/test) by the audit's extractor;
# each entry replays one legacy CSV.File call through both implementations.
# Hand-triaged entries carry a comment; see AUDIT.md for the ledger.

@testset "legacy corpus: CSV.File replay" begin
    # MANUAL basics.jl:23 [CSV.File]: agree("")
    # MANUAL basics.jl:26 [CSV.File]: agree(corpusfile("test_no_header.csv"); skipto=1, header=2)
    # MANUAL basics.jl:29 [CSV.File]: agree(corpusfile("test_float_in_int_column.csv"); types=[Int, Int, Int], strict=true)
    # MANUAL basics.jl:32 [CSV.File]: agree(corpusfile("int64_overflow.csv"); types=[Int8], strict=true)
    # MANUAL basics.jl:35 [CSV.File]: agree(corpusfile("test_newline_line_endings.csv"), types=Dict(1=>Integer))
    @case "basics:38" agree(IOBuffer(" \"a, b\", \"c\" "), skipto=1; label="basics:38")
    @case "basics:44" agree(IOBuffer(" \"2018-01-01\", \"1\" ,1,2,3"), skipto=1; label="basics:44")
    # MANUAL basics.jl:54 [CSV.File]: agree(corpusfile("test_types.csv"), types=Dict(:string=>Union{Missing,DateTime}))
    # MANUAL basics.jl:58 [CSV.File]: agree(corpusfile("test_types.csv"))
    # PINNED 1.0 DELTA: NUL is an accepted delimiter byte (0.10 rejected it)
    @case "basics:60" agree(IOBuffer("a\0b\n1\02\n"); delim='\0', label="basics:60", expect_delta="NUL is an accepted delimiter byte (0.10 rejected it)")
    # PINNED 1.0 DELTA: NUL is an accepted delimiter byte (0.10 rejected it)
    @case "basics:61" agree(IOBuffer("a\0b\n1\02\n"); delim="\0", label="basics:61", expect_delta="NUL is an accepted delimiter byte (0.10 rejected it)")
    @case "basics:63" agree(IOBuffer("a,b\n1,2\n"); header=3, label="basics:63")
    @case "basics:67" agree(IOBuffer("a,b\n1,2\n"); skipto=3, label="basics:67")
    @case "basics:71" agree(IOBuffer("a,b\n1,2\n"); skipto=3, label="basics:71")
    @case "basics:75" agree(IOBuffer("a,b\n1,2\n"); limit=0, label="basics:75")
    @case "basics:80" agree(IOBuffer("a,b\n1,1\n1,2\n1,3\n"); label="basics:80")
    # MANUAL basics.jl:96 [CSV.File]: agree(corpusfile("time.csv"); dateformat="H:M:S")
    # MANUAL basics.jl:101 [CSV.File]: agree(corpusfile("GSM2230757_human1_umifm_counts.csv"); ntasks=1)
    @case "basics:106" agree(IOBuffer("fullVisitorId,PredictedLogRevenue\n18966949534117,0\n39738481224681,0\n"), limit=3; label="basics:106")
    @case "basics:112" agree(IOBuffer("col1,col2\n1.0,hi"), limit=3; label="basics:112")
    @case "basics:116" agree(IOBuffer("x\n\",\"\n\",\""); label="basics:116")
    @case "basics:120" agree(IOBuffer("x\n1\n2\n"); label="basics:120")
    @case "basics:123" agree(IOBuffer("x,y\n1,\n2,\n"); label="basics:123")
    @case "basics:126" agree(IOBuffer("x y\n1 \n2 \n"); label="basics:126")
    @case "basics:129" agree(IOBuffer("x\ty\n1\t\n2\t\n"); label="basics:129")
    @case "basics:132" agree(IOBuffer("x|y\n1|\n2|\n"); label="basics:132")
    @case "basics:135" agree(IOBuffer("a;b;c\n1,1;2,2;3,3\n4,4;5,5;6,6\n"); decimal=',', label="basics:135")
    @case "basics:143" agree(IOBuffer("x\n1\n3.14"); label="basics:143")
    @case "basics:149" agree(IOBuffer("x\n1\n\n"), ignoreemptyrows=false; label="basics:149")
    @case "basics:155" agree(IOBuffer("x\n\n1\n"), ignoreemptyrows=false; label="basics:155")
    @case "basics:161" agree(IOBuffer("x\n\n1\n3.14\n"), ignoreemptyrows=false; label="basics:161")
    @case "basics:168" agree(IOBuffer("x\n1\n\n3.14\n"), ignoreemptyrows=false; label="basics:168")
    @case "basics:175" agree(IOBuffer("x\n1\n3.14\n\n"), ignoreemptyrows=false; label="basics:175")
    @case "basics:182" agree(IOBuffer("x\n1\nabc"); label="basics:182")
    @case "basics:188" agree(IOBuffer("x\n3.14\nabc"); label="basics:188")
    @case "basics:194" agree(IOBuffer("x\n1\n3.14\nabc"); label="basics:194")
    @case "basics:201" agree(IOBuffer("x\n\n1\n3.14\nabc"), ignoreemptyrows=false; label="basics:201")
    @case "basics:209" agree(IOBuffer("x\n1"), downcast=true, ignoreemptyrows=true; label="basics:209")
    @case "basics:212" agree(IOBuffer("x\n1\n$(typemax(Int16))"), downcast=true, ignoreemptyrows=true; label="basics:212")
    @case "basics:215" agree(IOBuffer("x\n1\n$(typemax(Int16))\n$(typemax(Int32))"), downcast=true, ignoreemptyrows=true; label="basics:215")
    @case "basics:218" agree(IOBuffer("x\n1\n$(typemax(Int16))\n$(typemax(Int32))\n$(typemax(Int64))"), downcast=true, ignoreemptyrows=true; label="basics:218")
    @case "basics:221" agree(IOBuffer("x\n1\n$(typemax(Int16))\n$(typemax(Int32))\n$(typemax(Int64))\n$(typemax(Int128))"), downcast=true, ignoreemptyrows=true; label="basics:221")
    @case "basics:224" agree(IOBuffer("x\n1\n$(typemax(Int16))\n$(typemax(Int32))\n$(typemax(Int64))\n$(typemax(Int128))\n3.14"), downcast=true, ignoreemptyrows=true; label="basics:224")
    @case "basics:227" agree(IOBuffer("x\n1\n$(typemax(Int16))\n$(typemax(Int32))\n$(typemax(Int64))\n$(typemax(Int128))\n3.14\nabc"), downcast=true, ignoreemptyrows=true; label="basics:227")
    @case "basics:230" agree(IOBuffer("x\n\n1"), downcast=true, ignoreemptyrows=false; label="basics:230")
    @case "basics:233" agree(IOBuffer("x\n\n1\n$(typemax(Int16))"), downcast=true, ignoreemptyrows=false; label="basics:233")
    @case "basics:236" agree(IOBuffer("x\n\n1\n$(typemax(Int16))\n$(typemax(Int32))"), downcast=true, ignoreemptyrows=false; label="basics:236")
    @case "basics:239" agree(IOBuffer("x\n\n1\n$(typemax(Int16))\n$(typemax(Int32))\n$(typemax(Int64))"), downcast=true, ignoreemptyrows=false; label="basics:239")
    @case "basics:242" agree(IOBuffer("x\n\n1\n$(typemax(Int16))\n$(typemax(Int32))\n$(typemax(Int64))\n$(typemax(Int128))"), downcast=true, ignoreemptyrows=false; label="basics:242")
    @case "basics:245" agree(IOBuffer("x\n\n1\n$(typemax(Int16))\n$(typemax(Int32))\n$(typemax(Int64))\n$(typemax(Int128))\n3.14"), downcast=true, ignoreemptyrows=false; label="basics:245")
    @case "basics:249" agree(IOBuffer("x\n\na\n"), pool=true, ignoreemptyrows=false; label="basics:249")
    @case "basics:255" agree(IOBuffer("x\na\n\n"), pool=true, ignoreemptyrows=false; label="basics:255")
    @case "basics:261" agree(IOBuffer("x\na\nb\na\nb\na\nb\na\nc\nd\ne\nf\ng\nh\ni\nj\nk\nl\nn\nm\no\np\nq\nr\n"), pool=0.5; label="basics:261")
    @case "basics:265" agree(IOBuffer("\"column name with \"\" escape character inside\"\n1\n"); label="basics:265")
    @case "basics:268" agree(IOBuffer("\"column name with \"\" escape character inside\",1\n,2"), transpose=true; label="basics:268")
    @case "basics:272" agree(IOBuffer("x\na\nb\n\"quoted field with \"\" escape character inside\"\n"), pool=true; label="basics:272")
    @case "basics:276" agree(IOBuffer("x\na\nb\n\"quoted field with \"\" escape character inside\"\n"), pool=true; label="basics:276")
    # PINNED 1.0 DELTA: unclosed quote is a reported problem, not a fatal error (warnings are data)
    @case "basics:281" agree(IOBuffer("x\n\"quoted field that never ends"); label="basics:281", expect_delta="unclosed quote is a reported problem, not a fatal error (warnings are data)")
    # PINNED 1.0 DELTA: unclosed quote is a reported problem, not a fatal error (warnings are data)
    @case "basics:282" agree(IOBuffer("x\nhey\n\"quoted field that never ends"); label="basics:282", expect_delta="unclosed quote is a reported problem, not a fatal error (warnings are data)")
    # PINNED 1.0 DELTA: unclosed quote is a reported problem, not a fatal error (warnings are data)
    @case "basics:283" agree(IOBuffer("x\n\n\"quoted field that never ends"); label="basics:283", expect_delta="unclosed quote is a reported problem, not a fatal error (warnings are data)")
    # PINNED 1.0 DELTA: unclosed quote is a reported problem, not a fatal error (warnings are data)
    @case "basics:284" agree(IOBuffer("x\n1\n\"quoted field that never ends"); label="basics:284", expect_delta="unclosed quote is a reported problem, not a fatal error (warnings are data)")
    # PINNED 1.0 DELTA: unclosed quote is a reported problem, not a fatal error (warnings are data)
    @case "basics:285" agree(IOBuffer("x\n1.0\n\"quoted field that never ends"); label="basics:285", expect_delta="unclosed quote is a reported problem, not a fatal error (warnings are data)")
    # PINNED 1.0 DELTA: unclosed quote is a reported problem, not a fatal error (warnings are data)
    @case "basics:286" agree(IOBuffer("x\na\n\"quoted field that never ends"), pool=true; label="basics:286", expect_delta="unclosed quote is a reported problem, not a fatal error (warnings are data)")
    @case "basics:289" agree(IOBuffer("x\nabc\n"), types=Int; label="basics:289")
    @case "basics:293" agree(IOBuffer("x\nabc\n"), types=Int, strict=true; label="basics:293")
    @case "basics:296" agree(IOBuffer("x,y,1\nx2,y2,2\n"), transpose=true, header=2; label="basics:296")
    @case "basics:302" agree(IOBuffer("x,y,1\nx2,y2,2\n"), transpose=true, header=1, skipto=3; label="basics:302")
    @case "basics:308" agree(IOBuffer("x,y,1\nx2,y2,2\n"), transpose=true, header=false, skipto=3; label="basics:308")
    @case "basics:314" agree(IOBuffer(""), transpose=true, header=false; label="basics:314")
    @case "basics:317" agree(IOBuffer(""), transpose=true, header=Symbol[]; label="basics:317")
    # MANUAL basics.jl:327 [CSV.File]: agree(IOBuffer(source); transpose=true)
    @case "basics:342" agree(IOBuffer("skip,a,,1,x,3\nskip,b,,4,5,6"); transpose=true, header=2, label="basics:342")
    @case "basics:346" agree(IOBuffer(",1,x,3\n,4,5,6"); transpose=true, header=[:a, :b], label="basics:346")
    # MANUAL basics.jl:350 [CSV.File]: agree(IOBuffer(source); transpose=true, limit=3)
    @case "basics:354" agree(IOBuffer("a,,1,x,3\nb,4"); transpose=true, label="basics:354")
    @case "basics:360" agree(IOBuffer("x\nabc\n"), header=Symbol[]; label="basics:360")
    @case "basics:364" agree(IOBuffer("x\ntrue\n\n"), ignoreemptyrows=false; label="basics:364")
    @case "basics:370" agree(IOBuffer("x\n2019-01-01\n\n"), ignoreemptyrows=false; label="basics:370")
    @case "basics:376" agree(IOBuffer("x\n2019-01-01\n\n"), types=Dict("x"=>Date), ignoreemptyrows=false; label="basics:376")
    # MANUAL basics.jl:382 [CSV.File]: agree(IOBuffer("int,float,date,datetime,bool,null,str,catg,int_float\n1,3.14,2019-01-01,2019-01-01T01:02:03,true,,hey,abc,2\n2,NaN,2019-01-02,2019-01-03T01:02:03,false,,there,abc,3.14\n"), pool=0.3)
    @case "basics:405" agree(IOBuffer("x\n1\n2\n3\n#4"); ignorerepeated=true, label="basics:405")
    @case "basics:408" agree(IOBuffer("x\n"), pool=true; label="basics:408")
    @case "basics:411" agree(IOBuffer("x\n1\n2\n3\n#4"), comment="#"; label="basics:411")
    # MANUAL basics.jl:416 [CSV.File]: agree(IOBuffer("x\n1\n2\n3\n#4"), types=[CSV_Foo])
    # MANUAL basics.jl:417 [CSV.File]: agree(IOBuffer("x\n1\n2\n3\n#4"), types=Dict(:x=>CSV_Foo))
    @case "basics:420" agree(IOBuffer("a,b,c\n1,2,3\n\n"); label="basics:420")
    @case "basics:423" agree(IOBuffer("zip\n11111-1111\n"), dateformat = "y-m-dTH:M:S.s"; label="basics:423")
    # MANUAL basics.jl:428 [CSV.File]: agree(`$(catcmd) $(corpusfile("test_basic.csv"))`)
    # MANUAL basics.jl:429 [CSV.File]: agree(corpusfile("test_basic.csv"))
    # MANUAL basics.jl:432 [CSV.File]: agree(corpusfile("randoms.csv.gz"); buffer_in_memory=true)
    @case "basics:435" agree(IOBuffer("thistime\n10:00:00.0\n12:00:00.0"); label="basics:435")
    @case "basics:440" agree(IOBuffer(",column2\nNA,2\n2,3"), missingstring=["NA"]; label="basics:440")
    @case "basics:444" agree(IOBuffer("x\n01:02:03\n\n04:05:06\n"), delim=',', ignoreemptyrows=false; label="basics:444")
    @case "basics:448" agree(IOBuffer("x\r\n1\r\n2\r\n3\r\n4\r\n5\r\n"), footerskip=3; label="basics:448")
    # MANUAL basics.jl:455 [CSV.File]: agree(IOBuffer(csv); comment="#", footerskip=1)
    @case "basics:462" agree(IOBuffer("h1234567890123456\t"^2262 * "lasthdr\r\n" * "dummy dummy dummy\r\n" * ("1.23\t"^2262 * "2.46\r\n")^10), skipto=3, ntasks=1; label="basics:462")
    @case "basics:467" agree(IOBuffer("date\n2020-05-05\n2020-05-32"); label="basics:467")
    @case "basics:470" agree(IOBuffer("time,date,datetime\n10:00:00.0,04/16/2020,2020-04-16 23:14:00\n"), dateformat=Dict(2=>"mm/dd/yyyy", 3=>"yyyy-mm-dd HH:MM:SS"); label="basics:470")
    # MANUAL basics.jl:477 [CSV.File]: agree(     IOBuffer("int8,uint32,bigint,bigfloat,dec64,csvstring\n1,2,170141183460469231731687303715884105727,3.14,1.02,hey there sailor\n2,,,,,\n");     types=[Int8, UInt32, BigInt, BigFloat, Dec64, CSVString] )
    # MANUAL basics.jl:494 [CSV.File]: agree(corpusfile("randoms.csv.gz"); types=[Int, CSVString, String, Float64, Dec64, Date, DateTime])
    # MANUAL basics.jl:499 [CSV.File]: agree(corpusfile("promotions.csv"); stringtype=PosLenString)
    # MANUAL basics.jl:502 [CSV.File]: agree(corpusfile("promotions.csv"); limit=7500, ntasks=2)
    @case "basics:505" agree(IOBuffer("1,2\r\n3,4\r\n\r\n5,6\r\n"); header=["col1", "col2"], ignoreemptyrows=true, label="basics:505")
    # MANUAL basics.jl:508 [CSV.File]: agree(corpusfile("escape_row_starts.csv"); ntasks=2)
    # MANUAL basics.jl:522 [CSV.File]: agree(path; ntasks=2)
    # MANUAL basics.jl:529 [CSV.File]: agree(IOBuffer("col1\nhey\nthere\nsailor"); stringtype=PosLenString)
    # MANUAL basics.jl:548 [CSV.File]: agree(corpusfile("big_types.csv"); stringtype=PosLenString, pool=false)
    @case "basics:561" agree(IOBuffer("col1\n1"); label="basics:561")
    # MANUAL basics.jl:584 [CSV.File]: agree(buf, header=["A", "B"])
    @case "basics:593" agree(IOBuffer("a\n1\n2\n3"); typemap=tm, label="basics:593")
    # MANUAL basics.jl:596 [CSV.File]: agree(IOBuffer("a\n1\n2\n3"); typemap=IdDict(Int=>String))
    @case "basics:600" agree(IOBuffer("""x,y
                                       a,b
                                       a,b
                                       a,b
                                       a,b
                                       a,b
                                       a,b
                                       a,b
                                       a,b
                                       a,b

                                       """), ignoreemptyrows=false; label="basics:600")
    @case "basics:616" agree(IOBuffer("a,b,c\n1,2,3\n4,5,6\n"); select=["a"], types=Dict(2=>Int8), label="basics:616")
    # MANUAL basics.jl:619 [CSV.File]: agree(transcode(GzipDecompressor, Mmap.mmap(corpusfile("randoms.csv.gz"))); types=Dict(:id=>Int32), select=["first"])
    @case "basics:624" agree(IOBuffer("col1,col2,col3\n1.0,2.0,3.0\n1.0,2.0,3.0\n1.0,2.0,3.0\n1.0,2.0,3.0\n"); ntasks=2, label="basics:624")
    @case "basics:629" agree(IOBuffer("col1,col2,col3,col4,col5\na,b,c,d,e\n" * "a,b,c,d\n"^101); label="basics:629")
    @case "basics:633" agree(IOBuffer("col1\n\n \n  \n1\n2\n3"), missingstring=["", " ", "  "], ignoreemptyrows=false; label="basics:633")
    @case "basics:637" agree(IOBuffer("a\n1"); label="basics:637")
    @case "basics:642" agree(IOBuffer("""
# 1'2
name
junk
1
"""), comment="#", header=2, skipto=4; label="basics:642")
    @case "basics:651" agree(IOBuffer("""
# 1'2"
name
junk
1
"""), comment="#", header=2, skipto=4; label="basics:651")
    @case "basics:661" agree(IOBuffer("Created Date\nToday\n"); label="basics:661")
    # MANUAL basics.jl:667 [CSV.File]: agree(IOBuffer(csv); skipto=1, footerskip=1)
    # MANUAL basics.jl:669 [CSV.File]: agree(IOBuffer(csv); skipto=1, footerskip=2)
    # MANUAL basics.jl:673 [CSV.File]: agree(IOBuffer(csv); skipto=1, footerskip=1)
    # MANUAL basics.jl:675 [CSV.File]: agree(IOBuffer(csv); skipto=1, footerskip=2)
    # MANUAL basics.jl:679 [CSV.File]: agree(IOBuffer(csv); skipto=1, footerskip=1)
    # MANUAL basics.jl:681 [CSV.File]: agree(IOBuffer(csv); skipto=1, footerskip=2)
    # MANUAL basics.jl:684 [CSV.File]: agree(IOBuffer(join(rand(["a", "b", "c"], 500), "\n")); header=false, ntasks=2)
    @case "basics:689" agree(IOBuffer("a, 0.1, 0.2, 0.3\nb, 0.4"); transpose=true, label="basics:689")
    @case "basics:695" agree(IOBuffer("x\n\0\n"); label="basics:695")
    @case "basics:700" agree(IOBuffer("x\n\"abc\"\n"); quoted=false, label="basics:700")
    # PINNED 1.0 DELTA: empty unquoted cell is ALWAYS missing (missingstring only ADDS spellings); 0.10's missingstring=nothing made empties present ""
    @case "basics:704" agree(IOBuffer("a,b,c\n1,2,3\n,null,4\n"), missingstring=nothing; label="basics:704", expect_delta="empty unquoted cell is ALWAYS missing (missingstring only ADDS spellings); 0.10's missingstring=nothing made empties present \"\"")
    @case "basics:714" agree(IOBuffer("a,b,c\n1,2,3"); types=Dict(4 => Float64), label="basics:714")
    @case "basics:715" agree(IOBuffer("a,b,c\n1,2,3"); types=Dict(:d => Float64), label="basics:715")
    @case "basics:716" agree(IOBuffer("a,b,c\n1,2,3"); types=Dict("d" => Float64), label="basics:716")
    @case "basics:718" agree(IOBuffer("a,b,c\n1,2,3"); dateformat=Dict(4 => "dd/mm/yyyy"), label="basics:718")
    @case "basics:719" agree(IOBuffer("a,b,c\n1,2,3"); dateformat=Dict(:d => "dd/mm/yyyy"), label="basics:719")
    @case "basics:720" agree(IOBuffer("a,b,c\n1,2,3"); dateformat=Dict("d" => "dd/mm/yyyy"), label="basics:720")
    @case "basics:722" agree(IOBuffer("a,b,c\n1,2,3"); pool=Dict(4 => true), label="basics:722")
    @case "basics:723" agree(IOBuffer("a,b,c\n1,2,3"); pool=Dict(:d => true), label="basics:723")
    @case "basics:724" agree(IOBuffer("a,b,c\n1,2,3"); pool=Dict("d" => true), label="basics:724")
    # MANUAL basics.jl:727 [CSV.File]: agree(     IOBuffer("a,b,c\n1,2,3");     types=Dict(4 => Float64),     dateformat=Dict(:e => "dd/mm/yyyy"),     pool=Dict("f" => true),     validate=false )
    # MANUAL basics.jl:737 [CSV.File]: agree(IOBuffer("a,b,c\n1,2,3\n3.14,5,6\n"); typemap=IdDict(Float64 => String))
    # MANUAL basics.jl:741 [CSV.File]: agree(IOBuffer(strip(""""column_name","data_type","is_nullable"\nfoobar,string,YES\nbazbat,timestamptz,YES""")))
    # MANUAL basics.jl:745 [CSV.File]: agree(@view(data[:]))
    # MANUAL basics.jl:759 [CSV.File]: agree(@view(parent[firstbyte:lastbyte]); buffer_in_memory)
    # MANUAL basics.jl:765 [CSV.File]: agree(io)
    # MANUAL basics.jl:770 [CSV.File]: agree(@view(parent[firstbyte:end]))
    # MANUAL basics.jl:776 [CSV.File]: agree(@view(parent[firstbyte:lastbyte]); footerskip=1)
    # MANUAL basics.jl:778 [CSV.File]: agree(UInt8[0xef, 0xbb, 0xbf]; footerskip=1)
    @case "basics:781" agree(IOBuffer("a,b,c\n1.2,3.4,5.6\n"); types=Float32, label="basics:781")
    @case "basics:785" agree(IOBuffer("a,b,c\n1.2,3.4,5.6\n"); types=BigFloat, label="basics:785")
    @case "basics:790" agree(codeunits("a,b,c\n1.2,3.4,5.6\n"); label="basics:790")
    # MANUAL basics.jl:795 [CSV.File]: agree(codeunits("a,b,c,d\n1,2,3.14,hey\n4,2,6.5,hey\n");                 types=(i, nm) -> i == 1 ? Int8 : i == 2 ? BigInt : i == 3 ? Float64 : String,                 pool=(i, nm) -> i == 2 ? true : nothing)
    # MANUAL basics.jl:821 [CSV.File]: agree(corpusfile("multithreadedpromote.csv"))
    # MANUAL basics.jl:831 [CSV.File]: agree(IOBuffer(data); select=[2], type=Int32)
    # MANUAL basics.jl:838 [CSV.File]: agree(IOBuffer(data); header=false, types=Dict(1 => String), typemap=IdDict(Int => Int8))
    # MANUAL basics.jl:840 [CSV.File]: agree(IOBuffer(data); header=false, types=Dict(1 => String), downcast=true)
    # MANUAL basics.jl:843 [CSV.File]: agree(IOBuffer(data); header=false, types=Dict(1 => String), typemap=Dict(Int => Int8), ntasks=16)
    @case "basics:847" agree(IOBuffer("a,b\n1,2\n3,"); label="basics:847")
    # MANUAL basics.jl:853 [CSV.File]: agree(IOBuffer(source))
    @case "basics:858" agree(IOBuffer("a,a,a\n"); label="basics:858")
    @case "basics:861" agree(IOBuffer("a,a_1,a\n"); label="basics:861")
    @case "basics:864" agree(IOBuffer("a,a,a_1\n"); label="basics:864")
    # MANUAL basics.jl:873 [CSV.File]: agree(IOBuffer(data); delim='|', normalizenames=true, stripwhitespace=false)
    # MANUAL basics.jl:875 [CSV.File]: agree(IOBuffer(data); delim='|', stripwhitespace=true)
    # MANUAL basics.jl:879 [CSV.File]: agree(IOBuffer(join((rand(("a,$(rand())", "b,$(rand())")) for _ = 1:10^6), "\n")), header=false, limit=10000)
    @case "basics:883" agree(IOBuffer("a\nfalse\n"); label="basics:883")
    # MANUAL basics.jl:889 [CSV.File]: agree(data; types=Dict(r"_col$" => Int16))
    # MANUAL basics.jl:892 [CSV.File]: agree(data; types=Dict(r"_column$" => Int16))
    # MANUAL basics.jl:894 [CSV.File]: agree(data; types=Dict(r"_col$" => Int16, "c" => Float16))
    # MANUAL basics.jl:899 [CSV.File]: agree(data; types=Dict(r"_col$" => Int16, :a_col => Int8))
    @case "basics:903" agree(IOBuffer("time,date1,date2\n10:00:00.0,04/16/2020,04/17/2022\n"); dateformat=Dict(r"^date"=>"mm/dd/yyyy"), label="basics:903")
    # MANUAL basics.jl:916 [CSV.File]: agree(IOBuffer(str); delim=" ", header=false, types=String)
    # MANUAL basics.jl:919 [CSV.File]: agree(IOBuffer(str); delim=" ", header=false, types=[Int8, Int16, Int32, Int64, Int128])
    # MANUAL basics.jl:922 [CSV.File]: agree(IOBuffer(str); delim=" ", header=false, types=(i,nm) -> (i == 5 ? Int8 : String))
    # MANUAL basics.jl:925 [CSV.File]: agree(IOBuffer(str); delim=" ", header=false, types=Dict(r".*" => Float16))
    # MANUAL basics.jl:930 [CSV.File]: agree(map(IOBuffer, ["name\n2\n", "name\n11\n"]))
    # MANUAL iteration.jl:3 [CSV.File]: agree(corpusfile(file))
    @case "runtests:28" agree(IOBuffer("X\nb\nc\na\nc"), pool=true; label="runtests:28")
    @case "runtests:34" agree(IOBuffer("X\nb\nc\na\nc"), pool=0.75; label="runtests:34")
    @case "runtests:40" agree(IOBuffer("X\nb\nc\n\nc"), pool=true, ignoreemptyrows=false; label="runtests:40")
    @case "runtests:45" agree(IOBuffer("X\nc\nc\n\nc\nc\nc\nc\nc\nc"), pool=0.25, ignoreemptyrows=false; label="runtests:45")
    # MANUAL runtests.jl:164 [CSV.File]: agree(IOBuffer(csv), select=[1, 3, 5])
    # MANUAL runtests.jl:169 [CSV.File]: agree(IOBuffer(csv), select=[:a, :c, :e])
    # MANUAL runtests.jl:174 [CSV.File]: agree(IOBuffer(csv), select=["a", "c", "e"])
    # MANUAL runtests.jl:179 [CSV.File]: agree(IOBuffer(csv), select=[true, false, true, false, true])
    # MANUAL runtests.jl:184 [CSV.File]: agree(IOBuffer(csv), select=(i, nm) -> i in (1, 3, 5))
    # MANUAL runtests.jl:189 [CSV.File]: agree(IOBuffer(csv), select=Int[])
    # MANUAL runtests.jl:193 [CSV.File]: agree(IOBuffer(csv), select=[1, 2, 3, 4, 5])
    # MANUAL runtests.jl:197 [CSV.File]: agree(IOBuffer(csv), drop=[2, 4])
    # MANUAL runtests.jl:202 [CSV.File]: agree(IOBuffer(csv), drop=[:b, :d])
    # MANUAL runtests.jl:207 [CSV.File]: agree(IOBuffer(csv), drop=["b", "d"])
    # MANUAL runtests.jl:212 [CSV.File]: agree(IOBuffer(csv), drop=[false, true, false, true, false])
    # MANUAL runtests.jl:217 [CSV.File]: agree(IOBuffer(csv), drop=(i, nm) -> i in (2, 4))
    # MANUAL runtests.jl:222 [CSV.File]: agree(IOBuffer(csv), drop=Int[])
    # MANUAL runtests.jl:226 [CSV.File]: agree(IOBuffer(csv), drop=[1, 2, 3, 4, 5])
    # MANUAL runtests.jl:479 [CSV.File]: agree(map(IOBuffer, data))
    # MANUAL runtests.jl:490 [CSV.File]: agree(map(IOBuffer, data))
    # MANUAL runtests.jl:500 [CSV.File]: agree(map(IOBuffer, data))
    # MANUAL runtests.jl:509 [CSV.File]: agree(map(IOBuffer, data))
    # MANUAL runtests.jl:512 [CSV.File]: agree(map(IOBuffer, data); source=:source)
    # MANUAL runtests.jl:516 [CSV.File]: agree(map(IOBuffer, data); source="source")
    # MANUAL runtests.jl:520 [CSV.File]: agree(map(IOBuffer, data); source="source"=>[1,2,3])
    # MANUAL runtests.jl:524 [CSV.File]: agree(map(IOBuffer, data); source=:source=>["1", "2", "3"])
    # MANUAL write.jl:312 [CSV.File]: agree(io; delim='\t')
    # MANUAL write.jl:338 [CSV.File]: agree(io, delim=char)
    # MANUAL write.jl:346 [CSV.File]: agree(tmp / "test.txt")
    # MANUAL testfiles.jl:9 [CSV.File]: agree(file isa IO ? file : corpusfile(file); kwargs...)
end
